version: '3'
services:
  images: maven
    dockerfile: Dockerfile
    volumes:
      - /tmp/
    images: tomcat
    dockerfile: Dockerfile_tc
    ports:
        - "8080:8080"
      volumes:
        - /tmp/:$CATALINA_HOME/webapps/