---
version: '3.7'
volumes:
        boxfuse:
services:
        build_boxfuse:
                volumes:
                        - boxfuse:/var/boxfuse/target/
                 build:
                       context: .
                         dockerfile: Dockerfile
        prod_boxfuse:
                volumes:
                        - boxfuse:/opt/tomcat/webapps/hello
                 build:
                       context: .
                         dockerfile: Dockerfile_tc
                ports:
                       - "8080:8080"
        command: "/opt/tomcat/bin/catalina.sh run"
---
